#ifndef GLOBALINCLUDE_H
#define GLOBALINCLUDE_H

#endif // GLOBALINCLUDE_H

#define DB_INIT 0
#define DB_SAVE 1
#define DB_LOAD 2

#define LOCALDB_REMOTEDBIP 0
#define LOCALDB_REMOTEDBPORT 1
#define LOCALDB_REMOTEDBNAME 2
#define LOCALDB_VERSION 3
#define LOCALDB_REMOTEDBUSERNAME 4
#define LOCALDB_REMOTEDBPASSWORD 5
#define LOCALDB_CURRENT_MACHINE_NAME 6

#define LANGUAGE_KOREAN 0
#define LANGUAGE_ENGLISH 1

#define TIMEOUT 1500

#define ON 1
#define OFF 0
